const fs = require('fs')
const path = require('path')
const { execSync } = require('child_process')

// Configure directories
const DATA_DIR = path.join(__dirname, 'data')
const PENDING_DIR = path.join(DATA_DIR, 'pending')
const PROCESSED_DIR = path.join(DATA_DIR, 'processed')
const IMPORT_SCRIPT = path.join(__dirname, 'import-csv.js')

// Ensure directories exist
if (!fs.existsSync(PENDING_DIR)) fs.mkdirSync(PENDING_DIR, { recursive: true })
if (!fs.existsSync(PROCESSED_DIR)) fs.mkdirSync(PROCESSED_DIR, { recursive: true })

console.log('\n' + '═'.repeat(60))
console.log('  INDICORE — Batch CSV Question Importer')
console.log('═'.repeat(60) + '\n')

// Get list of CSV files in the pending directory
const files = fs.readdirSync(PENDING_DIR).filter(file => file.endsWith('.csv'))

if (files.length === 0) {
    console.log('📂 No new CSV files found in scripts/data/pending/')
    console.log('   Add some files and run this script again.\n')
    process.exit(0)
}

console.log(`📁 Found ${files.length} file(s) to process.\n`)

let successCount = 0
let failCount = 0

for (const file of files) {
    console.log(`\n▶️  Processing: ${file}`)
    const filePath = path.join(PENDING_DIR, file)

    // Attempt to extract EXAM and YEAR from filename
    // Expected format: EXAM_YEAR_anything.csv (e.g., UPSC_2024_geography.csv)
    let examType = 'UPSC'
    let year = new Date().getFullYear()

    // Parse filename (e.g., "UPSC_2024_History.csv" -> parts: ["UPSC", "2024", "History.csv"])
    const parts = file.split('_')

    if (parts.length >= 2) {
        // e.g. 'UPSC'
        const possibleExam = parts[0].toUpperCase()
        // e.g. '2024'
        const possibleYear = parseInt(parts[1])

        if (possibleExam && isNaN(parseInt(possibleExam))) {
            examType = possibleExam
        }

        if (!isNaN(possibleYear) && possibleYear > 1900 && possibleYear <= new Date().getFullYear() + 1) {
            year = possibleYear
        } else if (parts.length >= 3) {
            // Check if year is in the 3rd part (e.g., PRELIMS_UPSC_2024.csv)
            const backupYear = parseInt(parts[2])
            if (!isNaN(backupYear) && backupYear > 1900 && backupYear <= new Date().getFullYear() + 1) {
                examType = possibleExam + (parts[1] ? `_${parts[1].toUpperCase()}` : '')
                year = backupYear
            }
        }
    }

    console.log(`   📝 Detected Exam: ${examType} | Year: ${year}`)

    try {
        // Execute the main import script synchronously
        const command = `node "${IMPORT_SCRIPT}" "${filePath}" "${examType}" ${year}`
        console.log(`   ⚙️  Running import...`)

        // Use stdio: 'inherit' to show the progress bar and logs directly in the terminal
        execSync(command, { stdio: 'inherit' })

        // If successful (no error thrown), move the file to processed directory
        const processedPath = path.join(PROCESSED_DIR, file)

        // Move file (rename)
        fs.renameSync(filePath, processedPath)

        // Check for any error files generated by import-csv.js and move them too
        const errorFile = file.replace('.csv', '_errors.json')
        const errorPathPending = path.join(PENDING_DIR, errorFile)
        const errorPathProcessed = path.join(PROCESSED_DIR, errorFile)

        if (fs.existsSync(errorPathPending)) {
            fs.renameSync(errorPathPending, errorPathProcessed)
            console.log(`   ⚠️  Moved error log to processed folder.`)
        }

        console.log(`   ✅ Successfully processed and moved to /processed/`)
        successCount++

    } catch (error) {
        console.error(`   ❌ Failed to process ${file}`)
        console.error(`   Error details: Command failed. Please check the logs above.`)
        failCount++
    }
}

console.log('\n' + '─'.repeat(60))
console.log('  🏁 Batch Processing Complete')
console.log(`  ✅ Successfully imported : ${successCount}`)
console.log(`  ❌ Failed to import      : ${failCount}`)
console.log('─'.repeat(60) + '\n')
